#!/usr/bin/env python3
"""
Bark Notify — Interactive Setup
================================
Parses your Bark URL and creates the .env configuration file.

Usage:
    python3 scripts/setup.py
    python3 scripts/setup.py "https://your-server.com/YOUR_KEY/test"
    python3 scripts/setup.py "https://your-server.com/YOUR_KEY/"

The Bark URL is the one you copy from the Bark iOS app.
"""
import os
import re
import sys
from pathlib import Path
from urllib import parse


SKILL_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = SKILL_DIR / ".env"
EXAMPLE_PATH = SKILL_DIR / ".env.example"


def parse_bark_url(url: str) -> tuple:
    """
    Parse a Bark URL into (base_url, device_key).

    Accepted formats:
        https://api.day.app/YOUR_KEY/
        https://api.day.app/YOUR_KEY/test push content
        https://example.com:8080/YOUR_KEY/anything
        https://example.com/YOUR_KEY
    """
    url = url.strip().strip('"').strip("'")

    parsed = parse.urlparse(url)
    if not parsed.scheme or not parsed.netloc:
        return None, None

    # Path segments: first non-empty segment is the key
    segments = [s for s in parsed.path.split("/") if s]
    if not segments:
        return None, None

    device_key = segments[0]
    base_url = f"{parsed.scheme}://{parsed.netloc}"

    return base_url, device_key


def prompt_input(prompt: str, default: str = "") -> str:
    """Prompt user for input with optional default."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    value = input(prompt).strip()
    return value if value else default


def main() -> int:
    print("=" * 50)
    print("  Bark Notify — Setup")
    print("=" * 50)
    print()

    base_url = ""
    device_key = ""

    # Try to parse URL from command-line argument
    if len(sys.argv) > 1:
        url = " ".join(sys.argv[1:])
        base_url, device_key = parse_bark_url(url)
        if base_url and device_key:
            print(f"  Parsed from URL:")
            print(f"    Server:  {base_url}")
            print(f"    Key:     {device_key}")
            print()
        else:
            print(f"  ⚠ Could not parse URL: {url}")
            print()
            base_url = ""
            device_key = ""

    # Interactive prompts for missing values
    if not base_url or not device_key:
        print("  Paste your Bark URL from the iOS app")
        print("  (e.g. https://api.day.app/YOUR_KEY/test)")
        print()
        url = prompt_input("  Bark URL")
        if url:
            base_url, device_key = parse_bark_url(url)
            if not base_url or not device_key:
                print("\n  ❌ Could not parse the URL.")
                print("  Expected format: https://server/KEY/...")
                return 1
        else:
            # Manual entry
            base_url = prompt_input("  Server URL", "https://api.day.app")
            device_key = prompt_input("  Device Key")

    if not device_key:
        print("\n  ❌ Device key is required.")
        return 1

    machine_name = prompt_input(
        "\n  Machine name (shown in notifications, optional)",
        os.uname().nodename.split(".")[0] if hasattr(os, "uname") else ""
    )

    # Confirm
    print()
    print("  Configuration:")
    print(f"    BARK_BASE_URL    = {base_url}")
    print(f"    BARK_KEY         = {device_key}")
    if machine_name:
        print(f"    BARK_MACHINE_NAME = {machine_name}")
    print()

    if ENV_PATH.exists():
        overwrite = prompt_input("  .env already exists. Overwrite? (y/N)", "N")
        if overwrite.lower() != "y":
            print("  Aborted.")
            return 0

    # Write .env
    lines = [
        "# Bark Push Notification Configuration",
        f"# Generated by setup.py",
        "",
        f"BARK_KEY={device_key}",
        f"BARK_BASE_URL={base_url}",
    ]
    if machine_name:
        lines.append(f"BARK_MACHINE_NAME={machine_name}")

    lines.extend([
        "",
        "# ---- Encryption (optional) ----",
        "# BARK_ENCRYPT_ALGORITHM=",
        "# BARK_ENCRYPT_MODE=",
        "# BARK_ENCRYPT_KEY=",
        "# BARK_ENCRYPT_IV=",
    ])

    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  ✅ Configuration saved to {ENV_PATH}")
    print()
    print("  Test it with:")
    print(f"    python3 {SKILL_DIR}/scripts/send_bark_notification.py \\")
    print(f'      --title "Hello" --body "Bark is ready!" --sound chime')
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
